name: Project pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7.16'
      - uses: iterative/setup-cml@v1
      - name: Project pipeline
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          pip install -r requirements.txt
          dvc repro

          git fetch --prune
          dvc metrics diff --show-md main > report.md

          ## Add figure to the report
          echo "## Validating results by region"
          echo "![inline](./report/confusion_matrix.png)" >> report.md
          cml comment create report.md
